### ISSUE TITLE
입출고대장 수정 요청사항 정리

### ISSUE THREAD

**Issue by gabypino** [onul-siktak/hoi_pasil_boon#5]
엑셀 파일을 보면, 입출고대장 sheet의 총발주(I5) 수식을 수정해야 한다. 
수정해야 하는 원래의 수식을 A 수식이라고 하겠다. A 수식은 이렇게 되어있다.
SUM($D$12,$D$16,$D$17,$D$1,$D$23,$D$33,$D$32,$D$34,$D$38,$D$39:$D$40,$D$47,$D$48:$D$49,$D$50,$D$52,$D$53,$D$54,$D$61,$D$62,$D$64,$D$75,D47,D67:D73,D20,)

A 수식을 새롭게 바꿔야한다. 새로 바꾸게 될 수식을 B 수식이라고 하겠다. 
B 수식은  
- 먼저 sheet4에 들어가서 1번그룹의 상품명을 확인한 다음에 
- 입출고대장에 가서 상품명 (column C)을 찾아서 
- 총발주의 숫자를 sum 한다.

이렇게 A 수식을 B 수식으로 바꾸면 총발주 수식에 들어가는 상품을 sheet4의 1번그룹으로 관리 할 수 있어서 수식의 수정이 필요 할 때 상품들을 더 빨리 찾고 다른 그룹의 상품과도 구별할 수 있게 된다.

**Comment by gabypino** [comment]
안녕하세요. 가비입니다. 과제 진행중에 문의가 있어서 연락 드립니다.

입출고대장의 소스용기(J5) 갯수 264개는 총발주 갯수 곱하기 6으로 되어있습니다.
Sheet4 에서 1번그룹에 해당하니까, Sheet2의 반찬 갯수를 보면 소스용기의 갯수를 곱하기 8로 계산해야 할 것 같은데 왜 그런건가요?
혹시 야채(쌈배추, 상추, 깻잎)가 소스용기 하나에 들어가게 되는건가요?

그리고 소스용기(J6) 갯수 53은 Sheet4에서 보면 5번그룹이고, Sheet2를 보면 5번 그룹은 무순, 회간장, 생와사비 3개로 되어있는데, 53 곱하기 3을 해야 하지 않나요?

**Comment by lianghao12** [comment]
안내가 미흡했네요, 쌈배추 상추 깻잎은 1개로 쳐서 들어갑니다. 

Sheet4에서 보면 5번그룹에 무순,회간장, 생와사비들어가는건 맞습니다.
거기에 들어가는 무순은 '중' 소스 용기임으로, 중소스용기인J의 수식을 보면 참치 대뱃살로 나옵니다.
그렇기에 곱하기3을 하지않고, 곱하기2가 맞습니다.

**Comment by lianghao12** [comment]
추가적으로 자세하게 말씀 드린다면, 
참다랑어 대뱃살회 1개에 무순,생와사비,회간장이 들어가는데
무순은 중소스용기
생와사비,회간장은 소스용기
로 들어가기 때문에

소스용기 J열 53은 소스용기만 치는거라서 중소스용기인 무순 용기는 해당하지 않기에 회간장, 생와사비만 소스용기 갯수로 쳐서 곱하기 2만 하면 된다
